"""empty message

Revision ID: abc6640c7549
Revises: Creating database
Create Date: 2021-05-16 12:33:43.256337

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'abc6640c7549'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'candles',
        sa.Column('candle_id', sa.String(length=36), nullable=False),
        sa.Column('id', sa.Integer(), nullable=True),
        sa.Column('at', sa.BigInteger(), nullable=True),
        sa.Column('from_', sa.BigInteger(), nullable=True),
        sa.Column('to', sa.BigInteger(), nullable=True),
        sa.Column('open', sa.Float(), nullable=True),
        sa.Column('close', sa.Float(), nullable=True),
        sa.Column('min', sa.Float(), nullable=True),
        sa.Column('max', sa.Float(), nullable=True),
        sa.Column('pair', sa.String(length=10), nullable=True),
        sa.Column('timeframe', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('candle_id'),
    )
    op.create_index(op.f('ix_candles_timeframe'), 'candles', ['timeframe'], unique=False)
    op.create_index('ix_pair_timeframe', 'candles', ['pair', 'timeframe'], unique=False)
    op.create_index('ix_pair_timeframe_at', 'candles', ['pair', 'timeframe', 'at'], unique=False)
    op.create_index('ix_pair_timeframe_to', 'candles', ['pair', 'timeframe', 'to'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pair_timeframe_to', table_name='candles')
    op.drop_index('ix_pair_timeframe_at', table_name='candles')
    op.drop_index('ix_pair_timeframe', table_name='candles')
    op.drop_index(op.f('ix_candles_timeframe'), table_name='candles')
    op.drop_table('candles')
    # ### end Alembic commands ###
